name: Deploy React (Vite) App to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Clean npm cache and reinstall dependencies
        run: |
          npm cache clean --force
          rm -f package-lock.json
          npm install

      - name: Build application
        run: npm run build

      - name: Prepare production deployment
        run: |
          # Create deployment directory
          mkdir -p deployment
          
          # Copy built files
          cp -r dist/* deployment/
          
          # Create optimized package.json for production
          cat > deployment/package.json << 'EOF'
          {
            "name": "porfolio-production",
            "version": "1.0.0",
            "engines": {
              "node": "20.x",
              "npm": "10.x"
            },
            "scripts": {
              "start": "serve -s . -p $PORT"
            },
            "dependencies": {
              "serve": "^14.2.4"
            }
          }
          EOF

      - name: Install production dependencies
        run: |
          cd deployment
          npm install --only=production --no-optional
          
          # Verify serve installation
          echo "Checking serve installation:"
          ls -la node_modules/.bin/ | grep serve || echo "serve binary not found"
          ./node_modules/.bin/serve --version || echo "serve version check failed"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_646B290AC1724693B164CD3D4947B353 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BD250A8452F0421B94ECF3BD50BFDC47 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A0A3E69559D143F8A11E4E6CD7432251 }}
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'albertoruiz'
          slot-name: 'Production'
          package: .
